### ISSUE TITLE
Hide Sidebar when not logged in

### ISSUE THREAD

**Issue by luisalisanne** [Trang217/Final-Project#59]
conditional rendering in Sidebar Component using AuthContext

**Comment by aliraza944** [comment]
Hi, If no one is assigned to this task I would like to have a go on it.

**Comment by luisalisanne** [comment]
Hey! This is actually a school project so we will be working on it ourselves, but I'm curious: how did you find this repo?

**Comment by aliraza944** [comment]
No problem. I was looking to contribute to the open-source projects saw your repo in the issues related to the javascript.
